import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-gray-300 py-4 pl-8">
          <ul className="flex gap-3">
            <li>
              <Link href="/">Home</Link>{" "}
            </li>
            <li>
              {" "}
              <Link href="/about">About</Link>{" "}
            </li>
            <li>Contact</li>
            <li>
              {" "}
              <Link href="/dashboard">Dashboard</Link>{" "}
            </li>
          </ul>
        </nav>
        <div className="p-8">{children}</div>
      </body>
    </html>
  );
}
